### ISSUE TITLE
Compile issue + killed signal

### ISSUE THREAD

**Issue by jfaddy** [rkbalgi/go#1]
Hi,
    I tried compiling this today and had a couple of issues:

1) error with MATTN package

# github.com/rkbalgi/go/paysim/ui
../../paysim/ui/paysim_mac_dialog.go:25: cannot use gtk.BUTTONS_OK (type gtk.ButtonsType) as type gtk.ResponseType in argument to dialog.AddButton

I managed to get the code to compile by making the following changes

ok_btn := dialog.AddButton("Generate", gtk.RESPONSE_OK)
cancel_btn := dialog.AddButton("Cancel", gtk.RESPONSE_CANCEL)

//	ok_btn := dialog.AddButton("Generate", gtk.BUTTONS_OK)
//	cancel_btn := dialog.AddButton("Cancel", gtk.BUTTONS_CANCEL)

2) It compiles with the following warning messages:

# github.com/mattn/go-gtk/pango
ld: warning: /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation, ignoring unexpected dylib file
# github.com/mattn/go-gtk/glib
ld: warning: /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation, ignoring unexpected dylib file
# github.com/mattn/go-gtk/gdkpixbuf
ld: warning: /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation, ignoring unexpected dylib file
# github.com/mattn/go-gtk/gdk
ld: warning: /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation, ignoring unexpected dylib file
# github.com/mattn/go-gtk/gtk
ld: warning: /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation, ignoring unexpected dylib file

3) If I run using GO RUN PAYSIM.GO  after ignoring the warning messages I get: 

signal: killed 

This is on Mac OSX Sierra 10.12.5

Thanks
James

**Comment by rkbalgi** [comment]
Hi James, I just tried this on my virtualbox linuxmint and seems to work fine with your suggested changes in the paysim/ui package.  I don't have a Mac to try this on, so unable to help at the moment.

This is slightly old and tried using a browser based version. Have you considered trying https://github.com/rkbalgi/isosim (a wiki https://github.com/rkbalgi/isosim/wiki)

**Comment by jfaddy** [comment]
Hi,
    Thanks for the prompt response and help on this. It turned out to be a
Mac OSX Sierra bug that is fixable by updating to latest version of GO.
Looking forward to playing around with your code. I'm curious... I notice
you have some code for simulating a HSM. Do you have experience dealing
directly with HSM machines?
best
James

**Comment by rkbalgi** [comment]
Hi James, OK, good luck. Yeah, I did happen on HSM machines a while ago. Thanks!
