### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by fhuwaidy** [rkbalgi/go#2]
I'm really new to Go and when I try to build go/iso_host, the following exceptions are raised:
`..\paysim\ui\paysim_mac_dialog.go:25: cannot use gtk.BUTTONS_OK (type gtk.ButtonsType) as type gtk.ResponseType in argument to dialog.AddButton
..\paysim\ui\paysim_mac_dialog.go:26: cannot use gtk.BUTTONS_CANCEL (type gtk.ButtonsType) as type gtk.ResponseType in argument to dialog.AddButton
..\paysim\ui\paysim_pin_dialog.go:28: cannot use gtk.BUTTONS_OK (type gtk.ButtonsType) as type gtk.ResponseType in argument to dialog.AddButton
..\paysim\ui\paysim_pin_dialog.go:29: cannot use gtk.BUTTONS_CANCEL (type gtk.ButtonsType) as type gtk.ResponseType in argument to dialog.AddButton`

Please your help

**Comment by rkbalgi** [comment]
Hi, Sorry for the late response. Can you pull in the new changes and try again?

**Comment by fhuwaidy** [comment]
Thank you, it works now :)
