### ISSUE TITLE
How to run Paysim Please?

### ISSUE THREAD

**Issue by edgars** [rkbalgi/go#3]
Hi, could you write instructions in how to tun Paysim?

I tried to run on my ubutun the simulator in Go+Web, and I got this error:
`go run isosim.go -httpPort 7777 -specDefFile specs\isoSpecs.spec -htmlDir .\html
isosim.go:5:2: cannot find package "github.com/rkbalgi/isosim/data" in any of:
	/usr/lib/go-1.6/src/github.com/rkbalgi/isosim/data (from $GOROOT)
	/home/edgar/go/src/github.com/rkbalgi/isosim/data (from $GOPATH)
isosim.go:6:2: cannot find package "github.com/rkbalgi/isosim/web/http_handlers" in any of:
	/usr/lib/go-1.6/src/github.com/rkbalgi/isosim/web/http_handlers (from $GOROOT)
	/home/edgar/go/src/github.com/rkbalgi/isosim/web/http_handlers (from $GOPATH)
isosim.go:7:2: cannot find package "github.com/rkbalgi/isosim/web/spec" in any of:
	/usr/lib/go-1.6/src/github.com/rkbalgi/isosim/web/spec (from $GOROOT)
	/home/edgar/go/src/github.com/rkbalgi/isosim/web/spec (from $GOPATH)
`

**Comment by rkbalgi** [comment]
Here's a small wiki page with an example - https://github.com/rkbalgi/isosim/wiki/Setting-Up
(There's also a Java based simulator here if here interested - https://github.com/rkbalgi/keedoh)
