### ISSUE TITLE
misc_test.go does not work

### ISSUE THREAD

**Issue by zangetsudo** [rkbalgi/go#4]
first i run the test case, use 
github.com/rkbalgi/go/iso8583 (master)
$ go test
An error came out that the "Handle" cannot be recognized.
then i omited the last few lines, then run again:
$ go test
exit status 3221225785
FAIL    github.com/rkbalgi/go/iso8583   0.014s

Another issue is that 

i have build iso_host.exe from github.com/rkbalgi/go/execs/iso_host, but after runing it, it turns out the same result.
i have a lot of research:
1. put a log message in the first line in main() of iso_host.go, but nothing cameout.
2. put a log message in every init() call, but nothing cameout.
3. omited pkgs from iso_host.go
- if i omited iso8583 pkg, that message cameout from main().

please tell me ,anything im doing wrong ?

**Comment by rkbalgi** [comment]
Hi, Sorry for the late response. The project depends on another project (https://github.com/mattn/go-gtk) which requires the GTK libraries. You can download those for windows here - [here](http://www.gtk.org/download/windows.php)

I don't have a windows machine at my disposal, but have tried it in the past and was found to be working. You can find more details here - (https://github.com/mattn/go-gtk)
